name: demo-actions

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubnutu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: run a smaple
        run: echo Hello worls
        
        
    
    
  
